version: '3'

services:
  web:
    container_name: controlcenter
    build: .
    ports:
      - 5010:80
      - 5011:443
    extra_hosts:
        - "vatsca.local:host-gateway"
    volumes:
      - ./:/app
