version: "3"

services:
  web:
    container_name: control-center
    build: .
    ports:
      - 8080:80
      - 8443:443
    extra_hosts:
        - "vatsca.local:host-gateway"
    volumes:
      - ./:/app
    env_file: .env

  db:
    container_name: database
    image: docker.io/library/mysql:9.0.1
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root

