---
name: "Test & Build"

on:
  push:
    paths-ignore:
      - "**.md"

env:
  IMAGE_NAME: vatsim-scandinavia/control-center
  TARGET_PLATFORMS: linux/amd64,linux/arm64

jobs:
  build-container:
    name: Build Control Center Container
    runs-on: ubuntu-latest
    steps:
      - name: configure docker buildx
        uses: docker/setup-buildx-action@v3

      - name: login to github container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: setup container metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=pr
            type=sha,event=branch,prefix=
            type=semver,event=tag,pattern=v{{version}}
            type=semver,event=tag,pattern=v{{major}}
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}

      - name: build & push container image
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:."
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: ${{ env.TARGET_PLATFORMS }}

  test-app:
    name: Control Center Test Suite
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Control Center
      uses: actions/checkout@v4
      with:
        path: controlcenter

    - name: Setup dependencies for Control Center
      uses: ./controlcenter/.github/actions/setup-dependencies
      with:
        path: controlcenter
        setup-node: true

    - name: Setup Control Center
      uses: ./controlcenter/.github/actions/setup-project
      with:
        path: controlcenter
        setup-node: true
        seed-database: true
      env:
        DB_CONNECTION: sqlite-testing

    - name: Execute unit and feature tests via PHPUnit
      run: ./vendor/bin/phpunit --color=always --testdox
      working-directory: ./controlcenter
